### ISSUE TITLE
composer install erases all the data in the database

### ISSUE THREAD

**Issue by mathieubrochard** [rouenssi-tnp/scims-backend#1]
Must find a way to update the database schema without erase all the data.

**Comment by mathieubrochard** [comment]
From the Propel [documentation](http://propelorm.org/documentation/02-buildtime.html):
> The schema.sql file will DROP any existing table before creating them, which will effectively erase your database.

There is no way to update the database schema without erase all the data.

**Comment by Blackrush** [comment]
Not even with migrations ?

**Comment by mathieubrochard** [comment]
@Blackrush I have edited https://github.com/rouenssi-tnp/scims-backend/issues/1#issuecomment-257342886
